version: '3'

services:
    mariadb:
        image: mariadb:10.5.16
        container_name: mariadb
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "mercado-livros"
        ports:
            - "3306:3306"
        volumes:
            - mariadb-volume:/var/lib/mysql
        networks:
            - mariadb-network

volumes:
    mariadb-volume:
        driver: local

networks:
    mariadb-network:
        driver: bridge