version: '3'

services:
    mysql:
        image: mariadb:10.0
        container_name: mariadb
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "mercado-livros"
        ports:
            - "3306:3306"
        volumes:
            - mysql-volume:/var/lib/mysql
        networks:
            - mysql-network

volumes:
    mysql-volume:
        driver: local

networks:
    mysql-network:
        driver: bridge